export const list = [
    {
        "title": "The Last Shadow Puppets - Sweet Dreams, TN - Later… with Jools Holland - BBC Two",
        "description": "See more at http://www.bbc.co.uk/later\nThe Last Shadow Puppets perform Sweet Dreams, TN on Later… with Jools Holland, BBC Two (24 May 2016)",
        "thumbnailUrl": "https://i.ytimg.com/vi/b3HfDsd_bZE/default.jpg",
        "videoAddedToPlaylistAt": "2019-05-21T01:50:56Z",
        "videoPublishedAt": "2016-05-24T22:22:34Z",
        "playlistHostedChannelName": "Ariel Milfont",
        "videoOwnerTitle": "BBC Music",
        "videoOwnerChannelId": "UCZtDUmC3W7j25XHZWFT_XgQ",
        "videoId": "b3HfDsd_bZE",
        "videoUrl": "https://www.youtube.com/watch?v=b3HfDsd_bZE",
        "videotags": "Last Shadow Puppets,Alex Turner,Miles Kane,Sweet Dreams TN,BBC Two,Later... with Jools Holland,Jools Holland",
        "categoryId": 10,
        "defaultAudioLanguage": "Not Present",
        "viewCount": 2139992,
        "likeCount": 27699,
        "favoriteCount": 0,
        "videoCommentCount": 936,
        "videoDuration": "PT4M31S"
    },
    {
        "title": "Cat Power- The Greatest",
        "description": "The Greatest by Cat Power",
        "thumbnailUrl": "https://i.ytimg.com/vi/QT9qM99l9Yk/default.jpg",
        "videoAddedToPlaylistAt": "2019-05-21T01:50:56Z",
        "videoPublishedAt": "2010-11-07T08:15:00Z",
        "playlistHostedChannelName": "Ariel Milfont",
        "videoOwnerTitle": "love01077",
        "videoOwnerChannelId": "UCyNko5gagd3L32gtZRqWwQQ",
        "videoId": "QT9qM99l9Yk",
        "videoUrl": "https://www.youtube.com/watch?v=QT9qM99l9Yk",
        "videotags": "cat power the greatest",
        "categoryId": 10,
        "defaultAudioLanguage": "Not Present",
        "viewCount": 6118143,
        "likeCount": 53495,
        "favoriteCount": 0,
        "videoCommentCount": 1378,
        "videoDuration": "PT3M23S"
    },
    {
        "title": "Phill Veras - Pode Vir Comigo (Acústico/MPB)",
        "description": "Você sabia que milhões de brasileiros descendem de judeus portugueses e que por isso podem conseguir o passaporte europeu? \nSiga @SENEOR no Instagram e acesse https://www.passaporte.eu para mais informações.\n\n*\n\nProduced and Directed by Marcos Seneor.\n\nNice - Côte d'Azur - France | São Luís - Maranhão - Brasil.\n\nPhill Veras\nSpotify: https://open.spotify.com/artist/3Bwyp...\nFacebook: https://www.facebook.com/PhillVeras/\nInstagram:  https://www.instagram.com/phillveras/",
        "thumbnailUrl": "https://i.ytimg.com/vi/9nP6U4uiZLA/default.jpg",
        "videoAddedToPlaylistAt": "2019-05-21T01:50:57Z",
        "videoPublishedAt": "2012-04-19T23:50:19Z",
        "playlistHostedChannelName": "Ariel Milfont",
        "videoOwnerTitle": "kinobaum",
        "videoOwnerChannelId": "UCoTLoeaA794SJQiIECK5ATA",
        "videoId": "9nP6U4uiZLA",
        "videoUrl": "https://www.youtube.com/watch?v=9nP6U4uiZLA",
        "videotags": "phill veras,mpb,voz e violão,pode vir comigo,brazil,bossa nova,brésil,acústico,nova mpb,marcos ponts,caetano veloso,marcelo camelo,silva,mallu magalhães,rubel,tiago iorc,cícero,castello branco,tim bernardes,los hermanos,banda do mar,rodrigo alarcon,tuyo,ana larousse,ana muller,leo fressato,versos que compomos na estrada,phillip long,francisco,el hombre,terno rei,vanguart,simonami,plutão já foi planeta,maglore,música brasileira,brazilian music",
        "categoryId": 10,
        "defaultAudioLanguage": "zxx",
        "viewCount": 3871859,
        "likeCount": 69346,
        "favoriteCount": 0,
        "videoCommentCount": 1375,
        "videoDuration": "PT4M42S"
    },
    {
        "title": "Blind Melon - Toes Across the Floor",
        "description": "Blind Melon \"Toes Across The Floor\" official music video from the album Soup. Subscribe to the official Blind Melon YouTube: http://bit.ly/BlindMelon-YouTube\n\nConnect with Blind Melon online: \nVisit the official Blind Melon website: https://blindmelon.com\nThe official Blind Melon merch shop: https://shop.blindmelon.com\nFollow Blind Melon on Instagram: https://instagram.com/blindmelonband\nLike Blind Melon on Facebook: https://facebook.com/blindmelonband\nFollow Blind Melon on Twitter: https://twitter.com/blindmelonband\n\nBlind Melon on Spotify:\nhttps://open.spotify.com/artist/5sD1ZLf2dGQ9gQ3YJl1eAd\n\nBlind Melon on Apple Music:\nhttps://music.apple.com/us/artist/blind-melon/533032\n\n#BlindMelon #ToesAcrossTheFloor",
        "thumbnailUrl": "https://i.ytimg.com/vi/3asQ7VS3LgU/default.jpg",
        "videoAddedToPlaylistAt": "2019-05-21T01:50:58Z",
        "videoPublishedAt": "2012-10-12T15:52:30Z",
        "playlistHostedChannelName": "Ariel Milfont",
        "videoOwnerTitle": "BlindMelonVEVO",
        "videoOwnerChannelId": "UClpuD2q1Gg1ixjPJMke-xMQ",
        "videoId": "3asQ7VS3LgU",
        "videoUrl": "https://www.youtube.com/watch?v=3asQ7VS3LgU",
        "videotags": "blind melon,blind melon toes across the floor,toes across the floor,toes across the floor blind melon,toes across the floor official music video,blind melon soup,blind melon official youtube,Shannon hoon,blind melon toes across the floor official video,rock,blind melon videos,soup,soup blind melon",
        "categoryId": 10,
        "defaultAudioLanguage": "Not Present",
        "viewCount": 1691252,
        "likeCount": 13114,
        "favoriteCount": 0,
        "videoCommentCount": 733,
        "videoDuration": "PT3M43S"
    },
    {
        "title": "eevee - Belas",
        "description": "https://eeveebeats.bandcamp.com/",
        "thumbnailUrl": "https://i.ytimg.com/vi/wktxNYjfvEg/default.jpg",
        "videoAddedToPlaylistAt": "2019-05-21T01:50:58Z",
        "videoPublishedAt": "2017-04-09T19:02:07Z",
        "playlistHostedChannelName": "Ariel Milfont",
        "videoOwnerTitle": "Irit Reddy",
        "videoOwnerChannelId": "UCKYKVLCWpBHP_l7Dhex6uzA",
        "videoId": "wktxNYjfvEg",
        "videoUrl": "https://www.youtube.com/watch?v=wktxNYjfvEg",
        "videotags": "portuguese,portuguese music,portugal,eevee,eevee beats,eevee belas,bela,eevee unexpected,house,beat tape,house music,beautiful,beautiful music,unexpected,eevee seeds,seeds,anime,anime music,cute music,cute,anime girl",
        "categoryId": 10,
        "defaultAudioLanguage": "Not Present",
        "viewCount": 440939,
        "likeCount": 11153,
        "favoriteCount": 0,
        "videoCommentCount": 411,
        "videoDuration": "PT3M"
    },
    {
        "title": "Cartola - Preciso Me Encontrar",
        "description": "vou por aí...",
        "thumbnailUrl": "https://i.ytimg.com/vi/fUjOfsoBhMY/default.jpg",
        "videoAddedToPlaylistAt": "2019-05-21T01:50:59Z",
        "videoPublishedAt": "2011-05-16T21:50:45Z",
        "playlistHostedChannelName": "Ariel Milfont",
        "videoOwnerTitle": "mariaperdida",
        "videoOwnerChannelId": "UCYpjC0aKAbwakOX9Ay5TEfg",
        "videoId": "fUjOfsoBhMY",
        "videoUrl": "https://www.youtube.com/watch?v=fUjOfsoBhMY",
        "videotags": "cartola",
        "categoryId": 10,
        "defaultAudioLanguage": "Not Present",
        "viewCount": 34716247,
        "likeCount": 400800,
        "favoriteCount": 0,
        "videoCommentCount": 17051,
        "videoDuration": "PT2M57S"
    },
    {
        "title": "Rubel - Quando Bate Aquela Saudade [Clipe Oficial]",
        "description": "Spotify ► https://goo.gl/Lbkxa7\nApple ► https://goo.gl/DhoiG8\nDeezer ►https://goo.gl/ma2ytQ\n\nDireção: Rubel\nProdução: Danielle Villanova\nRoteiro: Maíra Motta, Pedro Riguetti e Rubel \nFotografia: Tiago Rios e Guilherme Tostes\nArte: Luisa Pollo\nFigurino: Anouk Zee e Victoria Reis\nProdução de Elenco e Figuração: Cristiana Carvalho\nEdição: João Pedro Diaz e Rubel \nCorreção de Cor: Guilherme Tostes \n\nDedicado à memória de Theo Back \n\nRedes Sociais:\n▶ Facebook: https://www.facebook.com/RubelResponde\n▶ Instagram: @rubelrubelrubel\n\nSite Oficial:\n▶ www.rubelpearl.com.br\n\nPERSONAGENS\n(por ordem de aparição)\nBráulio Giordano\nOtávio Martins\nPaulo Giardini\nGerlinde Hauff\nPedro Zylbersztajn\nLili Noujaim \nLucas Lopes\nYasmin Teixeira\nIsaac Roque\nKim Ruggeri\nJulia Pimentel\nZé do Acordeom\nBreno Góes \nCatarina Saibro \nRosirene Visitação\nRubel\nDanielle Villanova\nFilipe Gimenez\nJR\nGiullia Beatriz\nSofia Starling\n\nNey Braga\nDjanira de Paula\nMaria Clara Contrucci\nOlivia Torres\nTelmo Bezzoco\nAlex Vicente\nPatrícia Oliveira\nAndré Farias\nIan Capillé\nArmando Amaral\nSimone Cerqueira\nLuana Arah\nJullye Luisa\n\nFIGURAÇÃO QUADRA\nBruno Fagundes Tebaldi\nCristian de Paula Souza\nDiogo Fagundes Tebaldi\nDiogo Marinho\nGabriel Albuquerque\nGabriel Nogueira\nMatheus Alexandre\nPablo de Souza\nSamuel Arcanjo\n\nFIGURAÇÃO LOTERIA\nCristiano Nogueira\nDaura Pacheco\nFranklin Brito da Silva\nGracinha\nIsabella Bicalho\nPaulo Mourão\nRômulo Barbosa\nTatiane Pacheco\n\nMETRÔ\nAnouk Zee Penido\nChloris Eleusis\nEric Meireles\nGabriela Secron\nGus Levy\nIgor Veloso\nIsmar Martins\nJoão Abtibol\nJulia Carino\nJulia Menna Barreto\nJulia Vargas\nLuciano Prateado\nLuisa Pollo\nCesar Pezzi \nMaria Inês Jordão\nNatália Langoni\nRodolfo Karvalho\nVictoria Reis\nVítor Henrique Guimarães\n\nAGRADECIMENTOS\nClube dos Funcionários\nVice Presidente Cláudio Augusto de Oliveira Ferreira \nAndréia Pires\nCarolina Benjamin\nCaio Branco\nJessica Vargas\nEmma Platais \nSandra Freitas\nLuis Cabelereiros Unissex\nAnna Carolina Guida\nAnna Roberta Guida\nAnna Helena Guida\nRoberto Guida\nColégio Pentágono\nProfessor Paulo Armando\nJorge Antônio\nRicardo Wagner \nCreche e Pré-Escola Oficina do Crescer \nStephanie Barbosa\nLotérica Trevo\nLuis e funcionários\nAeroporto Galeão\nLuis Fernando Lopes\nJued Abud Andari\nHerman Lima\nAcademia Body Move\nGerson Morgado\nRoberta Andrade e todos os amigos\nMarcio Cerqueira\nJéssica Quadros\nJoão Rabello\nAna Gimenez\nOsmar Martins\nDudu Martins\nHeloisa Helena de Sousa\nElisângela da Silva\nJuliana da Silva\nSara e Beta Visitação\nRoseli Andrade\nMarcos Villanova\nNathalia França\nVictor Clin\nSydney Golombek\nZhai Sichen\nNilton Marinho\nAndressa Rodrigues\nClaudia Regina\nMarcelina Soares\nPound5",
        "thumbnailUrl": "https://i.ytimg.com/vi/tMWpm_GOLaA/default.jpg",
        "videoAddedToPlaylistAt": "2019-05-21T01:50:59Z",
        "videoPublishedAt": "2015-09-27T23:07:22Z",
        "playlistHostedChannelName": "Ariel Milfont",
        "videoOwnerTitle": "Rubel",
        "videoOwnerChannelId": "UCesNI434dJImMNhU0JntoHg",
        "videoId": "tMWpm_GOLaA",
        "videoUrl": "https://www.youtube.com/watch?v=tMWpm_GOLaA",
        "videotags": "rubel,quando bate aquela saudade,clipe",
        "categoryId": 10,
        "defaultAudioLanguage": "pt",
        "viewCount": 56233663,
        "likeCount": 627168,
        "favoriteCount": 0,
        "videoCommentCount": 44235,
        "videoDuration": "PT6M45S"
    },
    {
        "title": "Slipknot - Snuff [OFFICIAL VIDEO]",
        "description": "Slipknot's music video for 'Snuff' from the album, All Hope Is Gone - available now on Roadrunner Records. Download now on iTunes: http://smarturl.it/allhope\n\nSite: http://slipknot1.com\niTunes: http://itunes.com/slipknot\nFacebook: http://facebook.com/slipknot\nTwitter: http://twitter.com/slipknot\nInstagram: http://instagram.com/slipknot\nTumblr: http://slipknot.tumblr.com\n\nLYRICS\nBury all your secrets in my skin\nCome away with innocence, \nAnd leave me with my sins\nThe air around me still feels like a cage\nAnd love is just a camouflage \nFor what resembles rage again...\n\nSo if you love me, let me go.\nAnd run away before I know.\nMy heart is just too dark to care.\nI can't destroy what isn't there.\nDeliver me into my fate -\nIf I'm alone I cannot hate\nI don't deserve to have you...\nMy smile was taken long ago\nIf I can change I hope I never know\n\nI still press your letters to my lips\nAnd cherish them in parts of me that savor every kiss\nI couldn't face a life without your light\nBut all of that was ripped apart when you refused to fight\n\nSo save your breath, I will not care.\nI think I made it very clear.\nYou couldn't hate enough to love.\nIs that supposed to be enough?\nI only wish you weren't my friend.\nThen I could hurt you in the end.\nI never claimed to be a saint...\nOoh, my own was banished long ago\nIt took the death of hope to let you go\n\nSo break yourself against my stones\nAnd spit your pity in my soul\nYou never needed any help\nYou sold me out to save yourself\nAnd I won't listen to your shame\nYou ran away - you're all the same\nAngels lie to keep control...\nOoh, my love was punished long ago\nIf you still care, don't ever let me know\nIf you still care, don't ever let me know...",
        "thumbnailUrl": "https://i.ytimg.com/vi/LXEKuttVRIo/default.jpg",
        "videoAddedToPlaylistAt": "2019-05-21T01:51:00Z",
        "videoPublishedAt": "2009-12-21T17:25:13Z",
        "playlistHostedChannelName": "Ariel Milfont",
        "videoOwnerTitle": "Slipknot",
        "videoOwnerChannelId": "UCOJZ1tna8yj8mAEITPkHNCQ",
        "videoId": "LXEKuttVRIo",
        "videoUrl": "https://www.youtube.com/watch?v=LXEKuttVRIo",
        "videotags": "Slipknot,Snuff,All Hope Is Gone,Psychosocial,Rock,Metal,PR. Brown,M Shawn Crahan,Clown,Nine,music,metal,heavy metal,Slipknot (band),Rock Music (Musical Genre),corey taylor,all hope is gone,Roadrunner Records (Record Label),Nu Metal (Radio Format),Alternative Metal (Musical Genre),Joey Jordison (Musical Artist)",
        "categoryId": 10,
        "defaultAudioLanguage": "Not Present",
        "viewCount": 140800426,
        "likeCount": 1104575,
        "favoriteCount": 0,
        "videoCommentCount": 46109,
        "videoDuration": "PT6M16S"
    },
    {
        "title": "Codinome Beija-Flor",
        "description": "Provided to YouTube by Som Livre\n\nCodinome Beija-Flor · Cazuza · Ezaquiel · Reinaldo Arias\n\nMelhores Momentos\n\n℗ 1985 Som Livre\n\nReleased on: 1989-01-01\n\nMusic  Publisher: Warner/Chappell\n\nAuto-generated by YouTube.",
        "thumbnailUrl": "https://i.ytimg.com/vi/IhRneNRypaw/default.jpg",
        "videoAddedToPlaylistAt": "2019-05-21T01:51:00Z",
        "videoPublishedAt": "2018-07-31T20:34:24Z",
        "playlistHostedChannelName": "Ariel Milfont",
        "videoOwnerTitle": "Cazuza - Topic",
        "videoOwnerChannelId": "UCRpECJZSh3wGVoNtHBLXA7Q",
        "videoId": "IhRneNRypaw",
        "videoUrl": "https://www.youtube.com/watch?v=IhRneNRypaw",
        "videotags": "Cazuza,Ezaquiel,Reinaldo Arias,Melhores Momentos,Codinome Beija-Flor",
        "categoryId": 10,
        "defaultAudioLanguage": "Not Present",
        "viewCount": 481196,
        "likeCount": 3513,
        "favoriteCount": 0,
        "videoCommentCount": 55,
        "videoDuration": "PT2M32S"
    },
    {
        "title": "Pot-Pourri: Karma / Danse Macabre (Ao Vivo | Bônus)",
        "description": "Provided to YouTube by Som Livre\n\nPot-Pourri: Karma / Danse Macabre (Ao Vivo | Bônus) · Scalene\n\nReal / Surreal (Deluxe)\n\n℗ 2013 Slap\n\nReleased on: 2013-08-14\n\nProducer: Diego Marx \nMusic  Publisher: Ed. Som Livre Edições Musicais\n\nAuto-generated by YouTube.",
        "thumbnailUrl": "https://i.ytimg.com/vi/hi5cSFEwwD0/default.jpg",
        "videoAddedToPlaylistAt": "2019-05-21T01:51:01Z",
        "videoPublishedAt": "2018-07-31T20:33:27Z",
        "playlistHostedChannelName": "Ariel Milfont",
        "videoOwnerTitle": "Scalene - Topic",
        "videoOwnerChannelId": "UCtLE9bMzGKja-GuYjMMmi8w",
        "videoId": "hi5cSFEwwD0",
        "videoUrl": "https://www.youtube.com/watch?v=hi5cSFEwwD0",
        "videotags": "Scalene,Real / Surreal (Deluxe),Pot-Pourri: Karma / Danse Macabre",
        "categoryId": 10,
        "defaultAudioLanguage": "Not Present",
        "viewCount": 688,
        "likeCount": 19,
        "favoriteCount": 0,
        "videoCommentCount": 1,
        "videoDuration": "PT6M56S"
    },
    {
        "title": "The Last Shadow Puppets - The Meeting Place (Live at Avatar Studios)",
        "description": "The Last Shadow Puppets perform \"The Meeting Place\" live at Avatar Studios in New York City in 2008. \nSubscribe to The Last Shadow Puppets on YouTube: http://bit.ly/TLSPVevo \n\nPurchase ‘The Age Of The Understatement’:\nDigital: http://po.st/TLSPiTunes   \nCD/LP: http://bit.ly/TLSPTAOTU \nStream: http://bit.ly/TLSPAOTUStrm \n\nFollow The Last Shadow Puppets: \nYouTube: http://bit.ly/TLSPVevo \nWebsite: http://bit.ly/TLSPW \nFacebook: http://bit.ly/TLSPFacebook \nTwitter: http://bit.ly/TLSPTW \nInstagram: http://bit.ly/TLSPINSTA \nSpotify: http://bit.ly/TLSPSP \nApple Music: http://po.st/TLSPApple \n\nFollow Domino Record Co:\nYouTube: http://smarturl.it/DominoYT\nWebsite: http://smarturl.it/DominoRecordCo\nFacebook: http://smarturl.it/DominoFB\nTwitter: http://smarturl.it/DominoTW\nInstagram: http://smarturl.it/DominoIN\n\nDir. Rob Hall.",
        "thumbnailUrl": "https://i.ytimg.com/vi/5JKKUxmVzeM/default.jpg",
        "videoAddedToPlaylistAt": "2019-05-21T01:51:01Z",
        "videoPublishedAt": "2008-05-06T22:18:21Z",
        "playlistHostedChannelName": "Ariel Milfont",
        "videoOwnerTitle": "Domino Recording Co.",
        "videoOwnerChannelId": "UCA8xMhX1DfxA8UKsfjn9vQg",
        "videoId": "5JKKUxmVzeM",
        "videoUrl": "https://www.youtube.com/watch?v=5JKKUxmVzeM",
        "videotags": "The last shadow puppets,alex turner,miles kane,the last shadow puppets live,age of the understatement,full album,lyrics,live session,interview,sweet dreams tn,miracle aligner,my mistakes were made for you,aviation,moonage daydream,TLSP,bad habits,everything you've come to expect,karaoke,standing next to me,the last shadow puppets meeting place,meeting place live,meeting place lyrics",
        "categoryId": 10,
        "defaultAudioLanguage": "Not Present",
        "viewCount": 4753705,
        "likeCount": 33010,
        "favoriteCount": 0,
        "videoCommentCount": 1484,
        "videoDuration": "PT3M5S"
    },
    {
        "title": "APESAR DE CIGANO- JORGE VERCILLO",
        "description": "Composição de Altay Veloso gravada no DVD LUAR DE SOL,\nGravado no teatro José de Alencar-Fortaleza-CE em 2013",
        "thumbnailUrl": "https://i.ytimg.com/vi/KT7W8IcVb8s/default.jpg",
        "videoAddedToPlaylistAt": "2019-05-21T01:51:02Z",
        "videoPublishedAt": "2014-08-19T08:10:58Z",
        "playlistHostedChannelName": "Ariel Milfont",
        "videoOwnerTitle": "Jorge Vercillo Oficial",
        "videoOwnerChannelId": "UCzZ1twZqCiQcZCGW1_uT71g",
        "videoId": "KT7W8IcVb8s",
        "videoUrl": "https://www.youtube.com/watch?v=KT7W8IcVb8s",
        "videotags": "jorge vercillo,apesar de cigano,luar de sol,vercilo,versillo,versilo,monalisa,que nem mare,homem aranha,andre neiva,anitta,thiaguinho",
        "categoryId": 10,
        "defaultAudioLanguage": "Not Present",
        "viewCount": 174907,
        "likeCount": 2048,
        "favoriteCount": 0,
        "videoCommentCount": 99,
        "videoDuration": "PT4M39S"
    },
    {
        "title": " Onde Anda Você \" - ( Vinicius de Moraes & Toquinho )",
        "description": "Onde Anda Você - Vinicius de Moraes & Toquinho\n\n( Vinicius de Moraes / Hermano Silva )\n\nE por falar em saudade\nOnde anda você\nOnde andam os seus olhos\nQue a gente não vê\nOnde anda esse corpo\nQue me deixou morto\nDe tanto prazer\n\nE por falar em beleza\nOnde anda a canção\nQue se ouvia na noite\nDos bares de então\nOnde a gente ficava\nOnde a gente se amava\nEm total solidão\n\nHoje eu saio na noite vazia\nNuma boemia sem razão de ser\nNa rotina dos bares\nQue apesar dos pesares\nMe trazem você\n\nE por falar em paixão\nEm razão de viver\nVocê bem que podia me aparecer\nNesses mesmos lugares\nNa noite, nos bares \nOnde anda você",
        "thumbnailUrl": "https://i.ytimg.com/vi/Gb5sbORA62w/default.jpg",
        "videoAddedToPlaylistAt": "2019-05-21T01:51:02Z",
        "videoPublishedAt": "2014-04-14T19:00:04Z",
        "playlistHostedChannelName": "Ariel Milfont",
        "videoOwnerTitle": "LeCommedieDellArte",
        "videoOwnerChannelId": "UC4gSDDUk0TJg6izeVUbb0mA",
        "videoId": "Gb5sbORA62w",
        "videoUrl": "https://www.youtube.com/watch?v=Gb5sbORA62w",
        "videotags": "Not Present",
        "categoryId": 29,
        "defaultAudioLanguage": "Not Present",
        "viewCount": 10771470,
        "likeCount": 221917,
        "favoriteCount": 0,
        "videoCommentCount": 5903,
        "videoDuration": "PT3M3S"
    },
    {
        "title": "Cícero - Açúcar ou adoçante? (clipe oficial)",
        "description": "http://www.facebook.com/cancoes.de.apartamento",
        "thumbnailUrl": "https://i.ytimg.com/vi/B4-nz0GPiJs/default.jpg",
        "videoAddedToPlaylistAt": "2019-05-21T01:51:03Z",
        "videoPublishedAt": "2012-06-29T22:58:10Z",
        "playlistHostedChannelName": "Ariel Milfont",
        "videoOwnerTitle": "MASSA PRODUTORA",
        "videoOwnerChannelId": "UCI_iR5C9bpBKmf3ofNksEJw",
        "videoId": "B4-nz0GPiJs",
        "videoUrl": "https://www.youtube.com/watch?v=B4-nz0GPiJs",
        "videotags": "Cícero,Canções,Apartamento,Açúcar,adoçante",
        "categoryId": 10,
        "defaultAudioLanguage": "Not Present",
        "viewCount": 8844646,
        "likeCount": 91191,
        "favoriteCount": 0,
        "videoCommentCount": 2209,
        "videoDuration": "PT4M24S"
    },
]